---
- name: Crear un archivo de prueba
  hosts: all
  become: false

  tasks:
    - name: Crear archivo
      ansible.builtin.copy:
        content: "Hola desde AWX"
        dest: /home/$USER/prueba-awx1.txt
